const express = require('express'), r = express.Router(), c = require('../controllers/adminController'), { requireUser } = require('../middleware/auth'), { role } = require('../middleware/roles');
r.use(requireUser, role('admin'), c.locals);
r.get('/', c.dashboard); r.get('/api/novedades', c.poll);
r.get('/pedidos', c.orders); r.get('/pedidos/exportar.csv', c.exportOrders); r.get('/pedidos/nuevo', c.newOrder); r.post('/pedidos/nuevo', c.createOrder);
r.get('/pedidos/:id', c.order); r.post('/pedidos/:id/estado', c.orderStatus); r.post('/pedidos/:id/asignar', c.orderAssign); r.post('/pedidos/asignar', c.orderAssign);
r.post('/pedidos/:id/pago', c.orderPayment); r.post('/pedidos/:id/nota', c.orderNote); r.post('/pedidos/:id/entrega', c.orderDelivery);
r.get('/productos', c.products); r.get('/productos/nuevo', c.productForm); r.get('/productos/:id/editar', c.productForm); r.post('/productos/guardar', c.saveProduct);
r.post('/productos/:id/alternar', c.toggleProduct); r.post('/productos/:id/eliminar', c.deleteProduct);
r.post('/subir', express.raw({ type: '*/*', limit: '8mb' }), c.upload);
r.get('/categorias', c.categories); r.post('/categorias', c.saveCategory); r.post('/categorias/:id/eliminar', c.deleteCategory);
r.get('/stock', c.stock); r.post('/stock/:id', c.adjustStock);
r.get('/promociones', c.promos); r.get('/promociones/nueva', c.promoForm); r.get('/promociones/:id/editar', c.promoForm); r.post('/promociones/guardar', c.savePromo); r.post('/promociones/:id/alternar', c.togglePromo); r.post('/promociones/:id/eliminar', c.deletePromo);
r.get('/clientes', c.clients); r.get('/clientes/nuevo', c.newClient); r.post('/clientes', c.saveClient); r.get('/clientes/:id', c.client);
r.get('/repartidores', c.riders); r.post('/repartidores', c.saveRider);
r.get('/entregas', c.deliveries); r.get('/mapa', c.map);
r.get('/consultas', c.inquiries('contacto')); r.get('/epigenetica', c.inquiries('epigenetica')); r.get('/thermomix', c.inquiries('thermomix')); r.post('/consultas/:id', c.updateInquiry);
r.get('/ventas', c.sales); r.get('/reportes', c.reports);
r.get('/configuracion', c.settings); r.get('/configuracion/:tab', c.settings); r.post('/configuracion/:tab', c.saveSettings);
r.get('/usuarios', c.users); r.post('/usuarios', c.saveUser); r.post('/usuarios/:id', c.userAction);
r.get('/contenido', c.content); r.get('/contenido/:tab', c.content); r.post('/contenido/:tab', c.saveContent);
r.post('/demo/restablecer', c.resetDemo);
module.exports = r;
